version: '3'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
            MYSQL_PASSWORD: heigel
            MYSQL_USER: bldrname
            MYSQL_DATABASE: boldare

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        depends_on:
            - mysql
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            
    web:
        container_name: boldare
        build: .
        ports:
            - 8081:80
        environment:
            DATABASE_URL: mysql://root:qwerty@mysql:3306/boldare
